language: node_js
node_js:
  - 11.9.0
before_install:
  - echo "//registry.npmjs.org/:_authToken=$(npx @manifoldco/cli export -p manifold-ui-ci | grep NPM_TOKEN | cut -f2 -d "=")" >> ~/.npmrc
stages:
  - test
  - publish
jobs:
  include:
    - stage: test
      name: 'Run Linters'
      script: npm run lint
    - stage: test
      name: 'Run tests'
      script: npm run test:coverage
    - stage: publish
      name: 'Publish to npm'
      script: 'npm run publish'
after_success:
  - npx codecov
cache: npm
